### ISSUE TITLE
On startup add_observer returns added events for every file

### ISSUE THREAD

**Issue by postmodern** [TwP/directory_watcher#19]
I noticed that when restarting jekyll, it claimed that 846 files had changed. I discovered that `add_observer` was yielding 846 added event objects, causing jekyll to regenerate _every_ single file.

**Comment by copiousfreetime** [comment]
I believe what you are seeing is the expected behavior in the default cause. On startup, all files that directory watcher has not seen before has events fired. I believe what you want is to ignore initial files are startup and just show those files that change since the last time

You probably want to take a look at http://rubydoc.info/gems/directory_watcher/1.4.1/DirectoryWatcher and look for 'Suppress Initial "added" Events' section

 `DirectoryWatcher.new( directory, :pre_load => true )`

**Comment by postmodern** [comment]
Ah ha. I opened an issue with Jekyll, since they should be filtering out the initial added events, by diffing the source files with `_site/**/*`.
