### ISSUE TITLE
Bug: DirectoryWatcher.new('/*') creates the directory named '*'

### ISSUE THREAD

**Issue by NV** [TwP/directory_watcher#2]
[NV/directory_watcher@c61d8/spec/directory_watcher_spec.rb](http://github.com/NV/directory_watcher/blob/c61d8/spec/directory_watcher_spec.rb)

Is it "by design"?

**Comment by TwP** [comment]
Yes, this is by design. The concept behind directory watcher is that it will watch exactly one directory. The files to keep an eye on are pared down by using one or more glob patterns to select a subset of files in the directory being watched.

Very early on in the life of directory watcher it was suggested that the directory to watch be created if it did not already exist. This is to prevent silent errors when the glob pattern was applied to a non-existent directory.

So, that's the concept behind the existing design.

Blessings,
TwP

**Comment by NV** [comment]
>  The concept behind directory watcher is that it will watch exactly one directory.

A little bit off-topic here. What glob pattern(s) should I use to match all HTML files in my home `~`, but exclude `~/Library` directory?
